### ISSUE TITLE
Installation instruction?

### ISSUE THREAD

**Issue by overseers-desk** [MJsaka/MJZhengMa#1]
I guess that the package folder is the compiled installation package so I unzipped "MJZhengMa-v1.0.zip" in it. Enable this package in System Preferences (security and privacy) and Double-click in OS X - nothing happens.

Expected:

Either prompt the user of the missing file ~/.config/MJZhengMa/Base.txt or show any message that leads user to their next action.

P.S. I also expected the directory ~/.config/MJZhengMa/ be automatically created upon double clicking the app but it didn't happen.

**Comment by MJsaka** [comment]
after unzipped , put "MJZhengMa.app" to "/Library/Input Methods/" or "~/Library/Input Methods/" directory, then add MJZhengMa in "System Preferances --> Keyboard-->Input Sources".
